In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
from sklearn.model_selection import train_test_split
sb.set()

In [2]:
df = pd.read_csv('healthy_diet_calorie_intake.csv')

In [3]:
df.describe(include = 'all')

,Person_ID,Age,Gender,Height_cm,Weight_kg,BMI,Activity_Level,Daily_Calorie_Requirement,Daily_Calorie_Consumed,Protein_Intake_g,Carbohydrate_Intake_g,Fat_Intake_g,Water_Intake_Liters,Diet_Type,Health_Status
count,6000,6000.000000,6000,6000.000000,6000.000000,6000.000000,6000,6000.000000,6000.000000,6000.000000,6000.000000,6000.000000,6000.000000,6000,6000
unique,6000,NaN,3,NaN,NaN,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,6,4
top,P0001,NaN,Male,NaN,NaN,NaN,Lightly Active,NaN,NaN,NaN,NaN,NaN,NaN,Balanced,Overweight
freq,1,NaN,2892,NaN,NaN,NaN,1627,NaN,NaN,NaN,NaN,NaN,NaN,1536,2500
mean,NaN,48.817167,NaN,168.592533,74.070933,26.094300,NaN,2286.223833,2490.520333,123.773150,288.035317,93.698417,2.734917,NaN,NaN
std,NaN,18.141837,NaN,9.160213,12.417877,4.162643,NaN,469.541134,602.279679,61.999158,123.914738,43.953993,0.681486,NaN,NaN
min,NaN,18.000000,NaN,145.000000,40.000000,12.900000,NaN,1223.000000,1000.000000,17.400000,-23.600000,23.200000,1.500000,NaN,NaN
25%,NaN,33.000000,NaN,161.700000,65.500000,23.300000,NaN,1941.000000,2057.000000,78.800000,229.100000,65.900000,2.200000,NaN,NaN
50%,NaN,48.000000,NaN,168.200000,74.100000,26.000000,NaN,2232.500000,2433.000000,108.900000,297.150000,82.300000,2.600000,NaN,NaN
75%,NaN,65.000000,NaN,175.200000,82.700000,28.900000,NaN,2581.250000,2859.000000,155.100000,366.125000,105.100000,3.100000,NaN,NaN
max,NaN,80.000000,NaN,198.600000,116.600000,44.000000,NaN,4079.000000,5158.000000,457.500000,729.700000,341.700000,5.000000,NaN,NaN

In [4]:
df.head()

,Person_ID,Age,Gender,Height_cm,Weight_kg,BMI,Activity_Level,Daily_Calorie_Requirement,Daily_Calorie_Consumed,Protein_Intake_g,Carbohydrate_Intake_g,Fat_Intake_g,Water_Intake_Liters,Diet_Type,Health_Status
0,P0001,50,Male,176.4,74.8,24.0,Very Active,2852,2625,183.0,16.9,202.8,3.3,Keto,Healthy
1,P0002,18,Female,167.6,75.5,26.9,Sedentary,1904,2044,90.1,306.5,50.8,1.9,Vegan,Overweight
2,P0003,68,Female,161.9,87.2,33.3,Lightly Active,2009,2540,222.7,281.3,58.2,2.4,High Protein,Obese
3,P0004,22,Female,169.3,66.9,23.3,Moderately Active,2318,2096,69.5,299.8,68.7,2.9,Balanced,Healthy
4,P0005,30,Male,179.1,75.3,23.5,Sedentary,2144,1937,32.9,285.6,73.7,2.2,Balanced,Healthy

In [5]:
df.shape

(6000, 15)

In [6]:
df.isnull().sum()

Person_ID                    0
Age                          0
Gender                       0
Height_cm                    0
Weight_kg                    0
BMI                          0
Activity_Level               0
Daily_Calorie_Requirement    0
Daily_Calorie_Consumed       0
Protein_Intake_g             0
Carbohydrate_Intake_g        0
Fat_Intake_g                 0
Water_Intake_Liters          0
Diet_Type                    0
Health_Status                0
dtype: int64

In [7]:
new_df = df.drop('Person_ID', axis = 1)

In [8]:
new_df.head()

,Age,Gender,Height_cm,Weight_kg,BMI,Activity_Level,Daily_Calorie_Requirement,Daily_Calorie_Consumed,Protein_Intake_g,Carbohydrate_Intake_g,Fat_Intake_g,Water_Intake_Liters,Diet_Type,Health_Status
0,50,Male,176.4,74.8,24.0,Very Active,2852,2625,183.0,16.9,202.8,3.3,Keto,Healthy
1,18,Female,167.6,75.5,26.9,Sedentary,1904,2044,90.1,306.5,50.8,1.9,Vegan,Overweight
2,68,Female,161.9,87.2,33.3,Lightly Active,2009,2540,222.7,281.3,58.2,2.4,High Protein,Obese
3,22,Female,169.3,66.9,23.3,Moderately Active,2318,2096,69.5,299.8,68.7,2.9,Balanced,Healthy
4,30,Male,179.1,75.3,23.5,Sedentary,2144,1937,32.9,285.6,73.7,2.2,Balanced,Healthy

In [9]:
new_df.columns

Index(['Age', 'Gender', 'Height_cm', 'Weight_kg', 'BMI', 'Activity_Level',
       'Daily_Calorie_Requirement', 'Daily_Calorie_Consumed',
       'Protein_Intake_g', 'Carbohydrate_Intake_g', 'Fat_Intake_g',
       'Water_Intake_Liters', 'Diet_Type', 'Health_Status'],
      dtype='object')

In [10]:
cols = ['Gender',
       'Activity_Level', 'Health_Status']

In [11]:
cols

['Gender', 'Activity_Level', 'Health_Status']

In [12]:
for col in cols:
    print(new_df[col].describe(include = 'unique'))

count     6000
unique       3
top       Male
freq      2892
Name: Gender, dtype: object
count               6000
unique                 5
top       Lightly Active
freq                1627
Name: Activity_Level, dtype: object
count           6000
unique             4
top       Overweight
freq            2500
Name: Health_Status, dtype: object

In [13]:
for col in cols:
    print(f"\n{'='*40}")
    print(f"{col}")
    print(f"{'='*40}")
    print(new_df[col].unique())

========================================
Gender
========================================
['Male' 'Female' 'Other']

========================================
Activity_Level
========================================
['Very Active' 'Sedentary' 'Lightly Active' 'Moderately Active' 'Athlete']

========================================
Health_Status
========================================
['Healthy' 'Overweight' 'Obese' 'Underweight']

In [14]:
for col in cols:
    if col == 'Gender':
        new_df[col] = new_df[col].map({'Male' : 0, 'Female' : 1, 'Other' : 2})
    elif col == 'Activity_Level':
        new_df[col] = new_df[col].map({'Sedentary':0, 'Lightly Active' : 1, 'Moderately Active': 2, 'Very Active': 3, 'Athlete': 4}) 
    elif col == 'Health_Status':
        new_df[col] = new_df[col].map({'Underweight': 0, 'Healthy': 1, 'Overweight': 2, 'Obese' : 3})

In [15]:
new_df[cols]

      Gender  Activity_Level  Health_Status
0          0               3              1
1          1               0              2
2          1               1              3
3          1               2              1
4          0               0              1
...      ...             ...            ...
5995       1               1              3
5996       1               0              2
5997       1               4              3
5998       1               1              2
5999       0               4              2

[6000 rows x 3 columns]

In [16]:
new_df.head()

,Age,Gender,Height_cm,Weight_kg,BMI,Activity_Level,Daily_Calorie_Requirement,Daily_Calorie_Consumed,Protein_Intake_g,Carbohydrate_Intake_g,Fat_Intake_g,Water_Intake_Liters,Diet_Type,Health_Status
0,50,0,176.4,74.8,24.0,3,2852,2625,183.0,16.9,202.8,3.3,Keto,1
1,18,1,167.6,75.5,26.9,0,1904,2044,90.1,306.5,50.8,1.9,Vegan,2
2,68,1,161.9,87.2,33.3,1,2009,2540,222.7,281.3,58.2,2.4,High Protein,3
3,22,1,169.3,66.9,23.3,2,2318,2096,69.5,299.8,68.7,2.9,Balanced,1
4,30,0,179.1,75.3,23.5,0,2144,1937,32.9,285.6,73.7,2.2,Balanced,1

In [17]:
new_df['Diet_Type'].unique()

array(['Keto', 'Vegan', 'High Protein', 'Balanced', 'Mediterranean',
       'Vegetarian'], dtype=object)

In [18]:
# diet_col = ['Keto', 'Vegan', 'High Protein', 'Balanced', 'Mediterranean',
#             'Vegetarian']

# diet_map = {diet: i for i, diet in enumerate(diet_col)}

# new_df['Diet_Type'] = new_df['Diet_Type'].map(diet_map)

In [19]:
new_df.head()

,Age,Gender,Height_cm,Weight_kg,BMI,Activity_Level,Daily_Calorie_Requirement,Daily_Calorie_Consumed,Protein_Intake_g,Carbohydrate_Intake_g,Fat_Intake_g,Water_Intake_Liters,Diet_Type,Health_Status
0,50,0,176.4,74.8,24.0,3,2852,2625,183.0,16.9,202.8,3.3,Keto,1
1,18,1,167.6,75.5,26.9,0,1904,2044,90.1,306.5,50.8,1.9,Vegan,2
2,68,1,161.9,87.2,33.3,1,2009,2540,222.7,281.3,58.2,2.4,High Protein,3
3,22,1,169.3,66.9,23.3,2,2318,2096,69.5,299.8,68.7,2.9,Balanced,1
4,30,0,179.1,75.3,23.5,0,2144,1937,32.9,285.6,73.7,2.2,Balanced,1

In [20]:
new_df = pd.get_dummies(new_df, columns = ['Diet_Type'], drop_first = True, dtype = int)

In [21]:
new_df.head(10)

,Age,Gender,Height_cm,Weight_kg,BMI,Activity_Level,Daily_Calorie_Requirement,Daily_Calorie_Consumed,Protein_Intake_g,Carbohydrate_Intake_g,Fat_Intake_g,Water_Intake_Liters,Health_Status,Diet_Type_High Protein,Diet_Type_Keto,Diet_Type_Mediterranean,Diet_Type_Vegan,Diet_Type_Vegetarian
0,50,0,176.4,74.8,24.0,3,2852,2625,183.0,16.9,202.8,3.3,1,0,1,0,0,0
1,18,1,167.6,75.5,26.9,0,1904,2044,90.1,306.5,50.8,1.9,2,0,0,0,1,0
2,68,1,161.9,87.2,33.3,1,2009,2540,222.7,281.3,58.2,2.4,3,1,0,0,0,0
3,22,1,169.3,66.9,23.3,2,2318,2096,69.5,299.8,68.7,2.9,1,0,0,0,0,0
4,30,0,179.1,75.3,23.5,0,2144,1937,32.9,285.6,73.7,2.2,1,0,0,0,0,0
5,36,0,175.7,73.2,23.7,4,3245,3434,268.3,333.0,114.3,4.5,1,1,0,0,0,0
6,29,0,172.3,93.6,31.5,1,2756,3147,312.3,267.7,91.9,2.6,3,1,0,0,0,0
7,65,1,164.9,80.1,29.5,2,2197,2609,108.3,412.6,58.4,2.6,2,0,0,0,1,0
8,42,1,159.5,80.7,31.7,0,1807,2180,216.4,194.7,59.5,2.5,3,1,0,0,0,0
9,74,1,156.9,67.5,27.4,1,1701,2008,60.5,271.6,75.5,2.4,2,0,0,1,0,0

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
inputs = new_df.drop(columns=[
    'Daily_Calorie_Requirement', 
    'BMI', 
    'Daily_Calorie_Consumed', 
    'Protein_Intake_g', 
    'Carbohydrate_Intake_g', 
    'Fat_Intake_g'
])

In [24]:
target = new_df['Daily_Calorie_Requirement']

In [25]:
x_train, x_test, y_train, y_test = train_test_split(inputs, target, test_size = 0.2, random_state = 42)

In [26]:
x_train

,Age,Gender,Height_cm,Weight_kg,Activity_Level,Water_Intake_Liters,Health_Status,Diet_Type_High Protein,Diet_Type_Keto,Diet_Type_Mediterranean,Diet_Type_Vegan,Diet_Type_Vegetarian
3897,59,1,163.8,65.0,2,2.6,1,0,0,0,0,0
5628,75,1,168.7,60.7,1,2.7,1,0,0,0,0,1
1756,28,1,165.6,66.9,2,2.9,1,0,0,0,0,1
2346,52,1,156.7,49.4,0,2.4,1,0,0,0,1,0
2996,68,0,173.0,85.2,1,2.3,2,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
3772,49,0,168.5,83.2,2,2.8,2,0,0,0,0,0
5191,36,1,154.9,74.3,1,2.4,3,0,0,0,0,1
5226,51,1,155.1,60.5,1,2.3,2,0,0,0,0,1
5390,30,0,181.2,66.2,0,2.1,1,0,0,0,0,1
860,23,1,156.4,55.1,2,2.7,1,0,0,0,0,1

In [27]:
y_train

3897    2016
5628    1659
1756    2260
2346    1398
2996    2302
        ...
3772    2687
5191    2006
5226    1742
5390    2009
860     2080
Name: Daily_Calorie_Requirement, Length: 4800, dtype: int64

In [28]:
from sklearn.ensemble import RandomForestRegressor

In [29]:
rf_model = RandomForestRegressor(n_estimators = 100, random_state = 42)

In [30]:
rf_model.fit(x_train, y_train)

RandomForestRegressor(random_state=42)

In [31]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np
y_pred = rf_model.predict(x_test)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print(f"Mean Absolute Error (MAE): {mae:.2f} kcal")
print(f"Root Mean Squared Error (RMSE): {rmse:.2f} kcal")
print(f"R² Score: {r2:.4f}")

Mean Absolute Error (MAE): 25.93 kcal
Root Mean Squared Error (RMSE): 39.33 kcal
R² Score: 0.9926

In [32]:
import joblib

In [33]:
joblib.dump(rf_model, 'calorie_requirement_prediction_RF.joblib')

['calorie_requirement_prediction_RF.joblib']

In [35]:
inputs.columns

Index(['Age', 'Gender', 'Height_cm', 'Weight_kg', 'Activity_Level',
       'Water_Intake_Liters', 'Health_Status', 'Diet_Type_High Protein',
       'Diet_Type_Keto', 'Diet_Type_Mediterranean', 'Diet_Type_Vegan',
       'Diet_Type_Vegetarian'],
      dtype='object')

In [40]:
inputs.dtypes

Age                          int64
Gender                       int64
Height_cm                  float64
Weight_kg                  float64
Activity_Level               int64
Water_Intake_Liters        float64
Health_Status                int64
Diet_Type_High Protein       int64
Diet_Type_Keto               int64
Diet_Type_Mediterranean      int64
Diet_Type_Vegan              int64
Diet_Type_Vegetarian         int64
dtype: object